name: super_nanny
description: SuperNanny â€” Babysitter Marketplace
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Networking
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # UI / Design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  timeago: ^3.6.1
  lottie: ^3.1.2

  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # Auth
  google_sign_in: ^6.2.1

  # Real-time Chat
  socket_io_client: ^2.0.3+1

  # Image
  image_picker: ^1.1.1
  image_cropper: ^7.0.1

  # Location
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Date/Time Picker
  table_calendar: ^3.1.2

  # Notifications
  flutter_local_notifications: ^17.1.2

  # Misc
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/brand/
    - assets/images/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brand/app_icon.png"
  min_sdk_android: 21
  web:
    generate: false

flutter_native_splash:
  color: "#7C3AED"
  image: assets/brand/splash_logo.png
  android_12:
    color: "#7C3AED"
    image: assets/brand/splash_logo.png
